[workspace]
members = [
    "crates/hidpp-core",
    "crates/logitech-devices",
    "crates/opengcontrol",
]
resolver = "2"

[workspace.dependencies]
hidapi = { version = "2.6" }
thiserror = "2"
serde = { version = "1", features = ["derive"] }
clap = { version = "4", features = ["derive", "color"] }
toml = "0.8"
serde_json = "1"
dirs = "5"
